steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - 'https://github.com/Lohith0590/GCPDevOps.git'
      - 'goog-rep'

  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'pull'
    dir: 'goog-rep'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'goog-rep/app.yaml'
    dir: 'goog-rep'

substitutions:
  _BUCKET_NAME: 'git-buck-1'
