steps:
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'rm -rf ./*'

  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Lohith0590/GCPDevOps.git', '.']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'index.html', 'gs://git-buck-1']

substitutions:
  _BUCKET_NAME: 'git-buck-1'
