steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Lohith0590/GCPDevOps.git', 'goog-rep']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'goog-repo/index.html', 'gs://git-buck-1']

substitutions:
  _BUCKET_NAME: 'git-buck-1'

